language: ruby
rvm:
  - 3.1
cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381  
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
 - sudo apt-get update
 - sudo apt-get upgrade ca-certificates
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
    - ca-certificates
cache: bundler
branches:
  only:
  - release
script:
  - JEKYLL_ENV=production bundle exec jekyll build --verbose --destination site
  - echo "coffeeanddata.ca" > ./site/CNAME
  - travis_retry bundle exec htmlproofer --assume-extension --allow-hash-href --ignore-status-codes 999,403,500 --ignore-urls "/twitter*/,/gstatic*/,/google*/,/tag*/" ./site
deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release