# Site setings
name: 'Coffee and Data'
title: 'Coffee and Data'
description: 'Data Blog by Marc-Olivier Arsenault'
tagline: 'Data Blog by Marc-Olivier Arsenault'
meta_description: 'Data Blog by Marc-Olivier Arsenault'
logo: 'assets/images/square_logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
url: https://coffeeanddata.ca
production_url: https://coffeeanddata.ca
feed_url: https://coffeeanddata.ca
#disqus: 'coffeeanddata'
mailchimp_url: '//coffeeanddata.us18.list-manage.com/subscribe/post?u=0d3439b2865b0b299714d7d5a&amp;id=bed66e1b11'
cover_image: bg5.jpg
# Add your GA Tracking Id
ga_analytics: G-PZTRVPSWT5


# Author
author:
  name: 'Marc-Olivier Arsenault'
  image: 'headshot.png'
  greetings: 'Coffee and Data'
  description: "Data Blog by Marc-Olivier Arsenault"
  quote: "Data Blog by Marc-Olivier Arsenault"
  bio: "Senior Data Development Manager @ Shopify"

# Contact form setings
email: marcolivier.arsenault@gmail.com
contact_page_description: "If you have any questions or you simply want to talk, feel free to send me a mail."
thankyou_page_description: "Your message has been successfully sent. Thanks!"

# Social links
twitter: 'MarcOlivierA'
facebook: 
github: 'marcolivierarsenault'
codepen: 
dribbble: 
medium: '@marcolivier.arsenault'
instagram:
pinterest:
linkedin: 'marcolivierarsenault'
producthunt: 
mastodon: '@marcolivier@mstdn.social'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
